# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME:   
GMAIL_PASSWORD:   
ADMIN_NAME:       
ADMIN_EMAIL:      
ADMIN_PASSWORD:   
MEMBER_NAME:      
MEMBER_EMAIL:     
MEMBER_PASSWORD:  
USER_NAME:        
USER_EMAIL:       
USER_PASSWORD:    
ROLES:            

SECERT_TOKEN:     
DEVISE_SECERT:
